data:
  class_path: dl_playground.data.datasets.WaymoMotionDataLoader
  init_args:
    root_path: data/waymo_open_dataset_motion_v_1_1_0
    train_interval: 8
    val_interval: 8
    train_batch_size: 32
    val_batch_size: 32
    num_workers: 16

model:
  class_path: dl_playground.models.vectornet2.VectorNet
  init_args:
    agent_in_channels: 43
    roadmap_in_channels: 26
    num_channels: 64
    num_subgraph_layers: 3
    num_global_graph_layers: 1
    num_global_graph_heads: 1
    global_graph_dropout: 0.1
    learning_rate: 0.001
    max_epochs: 80

trainer:
  max_epochs: 80
  accelerator: "gpu"
  devices: 1

  logger:
    - class_path: dl_playground.utils.logger.WandbLogger
      init_args:
        project: dl-playground
        entity: viv
        name: waymo_motion_vectornet_pe_no_me
        notes: "waymo_motion_vectornet"
        tags: ["VectorNet", "WaymoMotion"]
        save_code: True

  callbacks:
    - class_path: RichProgressBar
      init_args:
        leave: True
    - class_path: ModelCheckpoint
      init_args:
        filename: "epoch_{epoch:03d}_loss_{val/loss:.04f}"
        auto_insert_metric_name: False
        save_top_k: -1
        every_n_epochs: 1
    - LearningRateMonitor

  default_root_dir: wandb

  num_sanity_val_steps: 0

seed_everything: 23333
